name: PowerShell Script CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup PowerShell
      uses: actions/setup-powershell@v2

    - name: Check PowerShell script syntax
      run: pwsh -command "& { Get-ChildItem *.ps1 | ForEach-Object { Write-Host 'Checking:' $_.Name; Invoke-Expression '.\'+$_.Name } }
